#!/bin/bash

# Este script necessita privilégios root
if [[ "${UID}" -eq 0 ]]
then
	echo "Registrando uma nova conta de usuário local"
	echo ""
	
    # Receber dados com o comando read
	echo "A seguir informe os dados da conta"
	read -p "Nome de usuário: " USER_NAME
	read -p "Nome da pessoa responsável pela conta: " COMMENT
	read -p "Senha da conta: " PASSWORD
	
    # Criar o usuário com o script useradd atribuindo nome de
    # usuário e nome da pessoa responsável
	useradd -c "${COMMENT}" -m ${USER_NAME}

    # Em caso de erro ao criar o usuário
    if [[ "${?}" -ne 0 ]]
    then
	echo "Erro ao criar conta de usuário"
	exit 1
    fi
	
    # Atribuir a senha ao nome de usuário criado anteriormente,
    # através de um redirecionamento para o script chpasswd
	echo "${USER_NAME}:${PASSWORD}" | chpasswd

    # Em caso de erro ao atribuir a senha ao usuário
    if [[ "${?}" -ne 0 ]]
    then
	echo "Erro ao atribuir a senha de usuário"
	exit 1
    fi
	
    # Parte 4: Forçar a escolha de uma nova senha mais segura
	passwd -e ${USER_NAME}
	
# Em caso deste script não ser chamado pelo usuário root
else
	echo "Erro - este script deve ser executado com privilégios root"
	exit 1
fi

