#!/usr/bin/env python3

import secrets
import string

# Gerar uma senha forte de 32 caracteres
# contendo caracteres alfanuméricos e símbolos
def gerar_senha() -> str:
    charset = string.ascii_letters + string.digits + string.punctuation
    return "".join(secrets.choice(charset) for _ in range(32))

# Script chamado
if __name__ == "__main__":
    print(gerar_senha())