#!/usr/bin/env python3
import os
import subprocess
import sys

# Chamar programa que registra efetivamente a conta no sistema
def usuario_existe(nome_usuario: str) -> bool:
    try:
        comando_getent = ["getent", "passwd", nome_usuario]
        resultado_getent = subprocess.run(comando_getent, check=True, text=True)
        if resultado_getent.returncode != 0:
            print("Erro: Falha ao verficar existência de usuário com o comando getent.")
            sys.exit(1)
        else:
            if len(resultado_getent.stdout)>0:
                return True
            else:
                return False
    except Exception as e:
        print(f"Erro: {e}")
        sys.exit(1)

# Script chamado...
# É necessário passar como argumento
# o nome de usuário do qual deseja-se
# verificar se esta registrado no sistema
if __name__ == "__main__":
    # Se foi passado um argumento
    if len(sys.argv) > 1:
    # Obs: o elemento de indice zero
    # é o nome do script
        # Se o usuário existir...
        if usuario_existe(sys.argv[1]):
            print("Usuário registrado.")
        else:
            print("Usuário não registrado.")